### ISSUE TITLE
Help: Build error when loading images

### ISSUE THREAD

**Issue by holymp2006** [hayes0724/shopify-packer#11]
When my stylesheet contains url to images, like `url("../images/home/hero.jpg")` or `url(../images/fancybox_loading.gif)`, I get the following error, when I run `packer build`:
````
....
ERROR in ./src/styles/css/style.scss
Module build failed (from /****/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file
....
````
If I comment out all urls from the stylesheet, `build` works fine.

This is obviously related to the webpack config..
Please, do I need to include a file-loader? Or is there something else I'm missing?

**Comment by hayes0724** [comment]
On Shopify all files are flat and use CDN so you can't link to an image in css using `url(../images/fancybox_loading.gif)`

See [Styles with Liquid](https://github.com/hayes0724/shopify-packer#styles-with-liquid) for more information

Typically if you need an image inside the stylesheet you have a few options:
1. add to `theme.scss.liquid` using liquid, ex: `url({{ 'fancybox_loading.gif' | asset_img_url }})`
2. use the library CDN for css: `<link rel="stylesheet" type="text/css" href="jquery.fancybox.min.css">`
3. use the dist/css for the package. Note this is dependent on the library you are using
```shellscript
yarn add @fancyapps/fancybox
```
4. You could make the above URL's work while in development mode by adding the proper directory and settings to file loader but you would still need to do one of the 3 solutions above to deploy on Shopify.

I typically use option 3 (if it's supported), otherwise option 1 or 2.

```javascript
@import "~@fancyapps/fancybox/dist/jquery.fancybox.css"
```

This is a common issue with Shopify, especially when working with prebuilt HTML.

**Comment by holymp2006** [comment]
I really appreciate the suggestions.
However, the errors have more to do with `webpack` config, than how I set up the `src` directory.

I solved it by `npm` installing `file-loader`, and adding the following rules to the `prod.config.js` file:
````
{
   test: /\.(woff(2)?|png|svg|jpg|gif|ttf|otf|eot)$/,
   use: ["file-loader"],
 }
````

Thanks for an awesome package.
