### ISSUE TITLE
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file coroutine.cc, line 134.[BUG]

### ISSUE THREAD

**Issue by Teunel** [hayes0724/shopify-packer#145]
**Describe the bug**
Getting the above error when running packer start on a new M1 macbook pro.

**To Reproduce**
1. yarn global add @hayes0724/shopify-packer
2. packer start

**System (please complete the following information):**
 - OS: OSX 12.0
 - Node Version: v16.13.0
 - NPM Version: 8.1.0

**Packer (please complete the following information):**
 - Version v2.2.0

**Comment by vasilisakarelova** [comment]
I have the same error and i tried to install as new project, as well as an existing one

**Comment by mrpacman101** [comment]
@Teunel 
Have you tried installing node 14 or 15 instead? I run 14.17.3 or 15 stable.

**Comment by Kadreev** [comment]
Official message @ fibers page:
Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.

/Downgrading to v15 is not recommended, because doesn't have LTS - Long Term Support/

So I just used to downgrade to the latest 14.18.3 LTS and the issue is resolved.
