### ISSUE TITLE
[BUG] Editing JS doesn't trigger a page reload

### ISSUE THREAD

**Issue by GuillermoCasanova** [hayes0724/shopify-packer#19]
Here's the issue: 

Editing SCSS or HTML files does trigger a recompile, upload and then refresh of the page to show latest project. However, editing any JS files compiles it (console shows everything up to date), but the page does not refresh to show latest project. Instead, I have to manually refresh the page to view JS changes. Sometimes, JS changes don't come through at all. 

Any ideas as to why this happens, is this default behavior?

Specs:
Node v10.13 - 12.9.0 
Macbook Pro 
Sublime Text 
Terminal 

Thanks!

**Comment by hayes0724** [comment]
This is part of HMR (Hot Module Replacement) and is expected behavior for javascript. 

https://webpack.js.org/concepts/hot-module-replacement/

It will rerun you updated JS without a page refresh. If your code is not setup for HMR you will need to manually reload. 

Example:
```javascript
alert("hello world")
// this code will run again

$(document).ready(() => {
  // code here will not run again during HMR update
})
```

In the above example HMR adds the updates to be execute but the document ready event is already run so only the code above will actually trigger.

You can change/override the webpack config by using `dev.config.js` and `prod.config.js` in root directory

loader:

```
        {
          test: /\.js$/,
          exclude: config.get('commonExcludes'),
          loader: path.resolve(__dirname, '../hmr-alamo-loader.js'),
        },
```

plugins:

```
new webpack.HotModuleReplacementPlugin(),
```

**Comment by GuillermoCasanova** [comment]
Ah, not sure I quiet follow, but I implemented the code and got "config is not defined". Where do we define config? 

I have this code atm: 

const mergeDev = { };


  mergeDev.module = {
    rules: [
        {
          test: /\.js$/,
          exclude: config.get('commonExcludes'),
          loader: path.resolve(__dirname, '../hmr-alamo-loader.js'),
        }
    ]
  }

  mergeDev.plugins = [
  	new webpack.HotModuleReplacementPlugin()
  ]

module.exports = mergeDev
