### ISSUE TITLE
[BUG] SSL Cert generation and update on IP changes

### ISSUE THREAD

**Issue by mrpacman101** [hayes0724/shopify-packer#20]
**SSL key not recognized by packer**
Packer does not seem to recognize my SSL Keys.
I have just hacked my browser settings to allow non secure connection from localhost - since i had too many issues and less time to solve. I am looking at the docs and i think they are lacking some information. I have generated some certs on mac os and none of them worked. If anyone would share his solution or ways to solve - i would highly appreciate any help.

**To Reproduce**
1. Packer init & configure credentials in config.json
2. Create self-signed SSL Key 
3. localhost.cer stored in ~/.localhost_ssl
4. run packer "start" 
5. It will still complain about unsecure connection and invalid Cert 

**Expected behavior**
Expected as described in the documentation to work with self signed key.

**System (please complete the following information):**
 - OS: MacOS Catalina
 - Node Version 15.2.1
 - NPM Version 6.14.8
 - Browser Chrome 86 (latest)

**Packer:**
 - Version 1.2.1

**Theme:**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [False]

**Comment by puigandrew1** [comment]
Also having this issue

**Comment by mrpacman101** [comment]
Updated Bug Report

**Comment by hayes0724** [comment]
This is expected behavior, if your IP or hostname changes for a cert the browser should disallow it.

There are two approaches for SSL:
1. Tell browser to accept cert, since it's typically a local ip used this should not create any security issues.
2. Update the cert that is used by packer

Creating your own cert is not specific to packer and you can follow any general guide about creating local certs as long as it's in the path packer looks in (can be changed via `packer.config.js`)

For updating this on ip change with macos, Slate had a sample script: 

https://shopify.github.io/slate/docs/create-a-self-signed-ssl-certificate

Copy and paste the bash function into your terminal (or into your .bashrc file if you want to have it available in the future):

```bash
function ssl-check() {
    f=~/.localhost_ssl;
    ssl_crt=$f/server.crt
    ssl_key=$f/server.key
    b=$(tput bold)
    c=$(tput sgr0)

    # local_ip=$(ip route get 8.8.4.4 | head -1 | awk '{print $7}') # Linux Version
    local_ip=$(ipconfig getifaddr $(route get default | grep interface | awk '{print $2}')) # Mac Version
    # local_ip=999.999.999 # (uncomment for testing)

    domains=(
        "localhost"
        "$local_ip"
    )

    if [[ ! -f $ssl_crt ]]; then
        echo -e "\n🛑  ${b}Couldn't find a Slate SSL certificate:${c}"
        make_key=true
    elif [[ ! $(openssl x509 -noout -text -in $ssl_crt | grep $local_ip) ]]; then
        echo -e "\n🛑  ${b}Your IP Address has changed:${c}"
        make_key=true
    else
        echo -e "\n✅  ${b}Your IP address is still the same.${c}"
    fi

    if [[ $make_key == true ]]; then
        echo -e "Generating a new Slate SSL certificate...\n"
        count=$(( ${#domains[@]} - 1))
        mkcert ${domains[@]}

        # Create Slate's default certificate directory, if it doesn't exist
        test ! -d $f && mkdir $f

        # It appears mkcert bases its filenames off the number of domains passed after the first one.
        # This script predicts that filename, so it can copy it to Slate's default location.
        if [[ $count = 0 ]]; then
            mv ./localhost.pem $ssl_crt
            mv ./localhost-key.pem $ssl_key
        else
            mv ./localhost+$count.pem $ssl_crt
            mv ./localhost+$count-key.pem $ssl_key
        fi
    fi
}
```
