### ISSUE TITLE
Packer init PROJECT_NAME   not working

### ISSUE THREAD

**Issue by KhairAli** [hayes0724/shopify-packer#41]
**Describe the bug**
I am trying to  initialize default packer project , this issue is producing not only  in mac but also in my window machine

**To Reproduce**
1. npm i @hayes0724/shopify-packer -g
2. packer init my_packer_theme
3. ✖ There was an error:
ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/@hayes0724/shopify-packer/docs/my-packer-theme/packer-blank-theme-v1.0.9'
Removing directory /usr/local/lib/node_modules/@hayes0724/shopify-packer/docs/my-packer-theme...

**Expected behavior**
should create  packer empty project

**Screenshots**
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/14020488/104465844-4ee62500-55d6-11eb-8a9f-bc1cbc83482c.png">

**System (please complete the following information):**
 - OS: [macOS Catalina version 10.15.6]
 - Node Version [14.15.4]
 - NPM Version [6.14.10]
 

**Packer (please complete the following information):**
 - Version [1.3.2]

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [e.g. True]
 - Version [1.0.9]

**Comment by hayes0724** [comment]
Packer blank theme now uses v in tag names, example: v1.0.9

When downloading the theme from the zip file has `v1.0.9` in its name. When extracted it only contains the numbers `1.0.9` causing the extraction to fail since it can't find the correct folder.

This is fixed in Packer [1.3.4](https://github.com/hayes0724/shopify-packer/releases/tag/1.3.4)
