### ISSUE TITLE
[BUG] Assets Themekit does not upload

### ISSUE THREAD

**Issue by Steda-dev** [hayes0724/shopify-packer#84]
Does not upload the js files in the assets folder after the file is changed while running the 'watch' command. 
The changed file is visable in the dist folder.

1. packer watch
2. change the js file
3. does not upload the file, but changes are made in the dist folder
4. packer deploy
5. now it works

**System:**
 - Windows 10
 - Node Version 14.16.1
 - NPM Version 6.14.12
 - Browser egde

**Packer:**
 - Version v2.1.5

**Comment by marioloncarek** [comment]
@Steda-dev can confirm fonts not being copied to dist as assets in v2.1.5, but in previous packer version they did, can you help @hayes0724 please?

**Comment by yashghelani** [comment]
I’m facing this same exact problem

**Comment by yashghelani** [comment]
I’m facing this same exact problem

**Comment by yashghelani** [comment]
I’m facing this same exact problem

**Comment by hayes0724** [comment]
@yashghelani @Steda-dev It should not upload any files unless they are liquid, when using start/watch the files are served locally and updated with hmr. For hmr to work the script and style tags snippet needs to have local ip. If you run watch (vs start) without having this uploaded to Shopify you will not see updates. I use start almost every time to make sure, watching is only good for temporary breaks (ex you just ran start recently). 

Not uploading non liquid files is expected behavior, Are you not seeing changes happen after editing non liquid files?

1. When using watch do any changes happen after editing a file? ex. adding alert message on theme.js
2. Have you tried start?
3. If you run deploy it will upload all the files but hmr will not work (start/watch) you would see your previous changes on the first load. This is because deploy makes a production version using Shopify's CDN and start/watch need local address to avoid using CDN.

When you are having this issue can you take a screenshot of the network tab with the layout.theme.js file selected?

![Desktop-screenshot (4)](https://user-images.githubusercontent.com/12520996/116319246-caca3e80-a77b-11eb-97dc-0f34229f9399.png)

Also I have noticed a similar issue when switching to start/watch after running a deploy, it's solved by deleting the dist folder before running any commands. In v2.1.9 I changed the webpack cleans the dist folder so this should no longer be needed.

**Comment by marioloncarek** [comment]
@hayes0724 i managed to work around with fonts by manually copy them from src/fonts to src/assets and then they are uploaded, can you please confirm this is correct process? thanks

**Comment by hayes0724** [comment]
@marioloncarek You can/should add fonts to the assets folder. The src/assets folder is flattened during build so if you use src/assets/fonts it will be moved automatically to dist/assets

**Comment by marioloncarek** [comment]
@hayes0724 thank you! if that is the case i must say everything works correctly for me, sorry for misunderstanding

**Comment by hayes0724** [comment]
@Steda-dev @yashghelani Are you still having issues with this?

**Comment by yashghelani** [comment]
@hayes0724 I think my issue was with the version of node I was using, i.e. v16. I’m using the LTS version now and the npm version that comes with it. That has solved all the issues for me. I’m afraid I cannot provide more information about the issue I was facing with v16 as I didn’t get time to test and quickly downgraded to the LTS version. If I can be of help in any other way by providing any information, let me know. I’ll be happy to help.

**Comment by bstarr322** [comment]
I still have this issue..
Does not upload the js files in the assets folder after the file is changed while running the `yarn start` command.
The changed file is visable in the dist folder.

Steps to reproduce the behavior:
- packer watch
- change the js file
- does not upload the file, but changes are made in the dist folder
- packer deploy
- now it works

System:

- Windows 10
- Node Version 12.22.9
- NPM Version 6.14.15
- Browser: Google Chrome

Packer:
- Version v2.2.0
